### ISSUE TITLE
Beta testing

### ISSUE THREAD

**Issue by MiRoVaGo** [MiRoVaGo/pRecipe#1]
test the functions download_data and reformat_data

**Comment by Rajani462** [comment]
>download_gpcc(folder, 2.5)
trying URL 'ftp://ftp.cdc.noaa.gov/Datasets/gpcc/full_v2018/precip.mon.total.2.5x.25.v2018.nc'
Error in download.file(file_url, file_destination, mode = "wb") : 
  cannot open URL 'ftp://ftp.cdc.noaa.gov/Datasets/gpcc/full_v2018/precip.mon.total.2.5x.25.v2018.nc'
In addition: Warning message:
  In download.file(file_url, file_destination, mode = "wb") :
  InternetOpenUrl failed: ''

**Comment by Rajani462** [comment]
Errors in TRMM and GPM downloads.
Error in download.file(file_url, file_destination, mode = "wb") : 
  cannot open URL 'https://

**Comment by MiRoVaGo** [comment]
> > download_gpcc(folder, 2.5)
> > trying URL 'ftp://ftp.cdc.noaa.gov/Datasets/gpcc/full_v2018/precip.mon.total.2.5x.25.v2018.nc'
> > Error in download.file(file_url, file_destination, mode = "wb") :
> > cannot open URL 'ftp://ftp.cdc.noaa.gov/Datasets/gpcc/full_v2018/precip.mon.total.2.5x.25.v2018.nc'
> > In addition: Warning message:
> > In download.file(file_url, file_destination, mode = "wb") :
> > InternetOpenUrl failed: ''

I fixed the link it should be working now (there was a missing ".")

**Comment by MiRoVaGo** [comment]
> Errors in TRMM and GPM downloads.
> Error in download.file(file_url, file_destination, mode = "wb") :
> cannot open URL 'https://

@Rajani462 could you provide the full error message?
Also, when did you try? Perhaps GES DISC was still under maintenance.
Last, did you follow the instructions to create an EarthData account and to link it to GES DISC?

**Comment by Rajani462** [comment]
I tried it yesterday and today as well and it gives the same error, but manually it always downloads the files.
The error message: 
trying URL 'https://rkpradhan462@gmail.com:mypassword@gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGM.06/2003/3B-MO.MS.MRG.3IMERG.20030101-S000000-E235959.01.V06B.HDF5'
Error in download.file(file_url, file_destination, mode = "wb") : 
  cannot open URL 'https://rkpradhan462@gmail.com:mypassword@gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGM.06/2003/3B-MO.MS.MRG.3IMERG.20030101-S000000-E235959.01.V06B.HDF5'
In addition: Warning message:
In download.file(file_url, file_destination, mode = "wb") :
  InternetOpenUrl failed: 'The URL is invalid'

**Comment by MiRoVaGo** [comment]
> I tried it yesterday and today as well and it gives the same error, but manually it always downloads the files.
> The error message:
> trying URL 'https://rkpradhan462@gmail.com:mypassword@gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGM.06/2003/3B-MO.MS.MRG.3IMERG.20030101-S000000-E235959.01.V06B.HDF5'
> Error in download.file(file_url, file_destination, mode = "wb") :
> cannot open URL 'https://rkpradhan462@gmail.com:mypassword@gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGM.06/2003/3B-MO.MS.MRG.3IMERG.20030101-S000000-E235959.01.V06B.HDF5'
> In addition: Warning message:
> In download.file(file_url, file_destination, mode = "wb") :
> InternetOpenUrl failed: 'The URL is invalid'

@Rajani462 You didn't follow the instructions for EarthData and linking to GES DISC :)
Earthdata username is not an email

**Comment by MiRoVaGo** [comment]
Updated the functions to encode special characters
@Rajani462 Could you test again?
Also, could you confirm if gpcc error was fixed?

**Comment by Rajani462** [comment]
GPM and TRMM downloads are working now. 
But, the gpcc error still exists.
Error message: download_gpcc(folder, 2.5)
trying URL 'ftp://ftp.cdc.noaa.gov/Datasets/gpcc/full_v2018/precip.mon.total.2.5x.2.5.v2018.nc'
Error in download.file(file_url, file_destination, mode = "wb") : 
  cannot open URL 'ftp://ftp.cdc.noaa.gov/Datasets/gpcc/full_v2018/precip.mon.total.2.5x.2.5.v2018.nc'
In addition: Warning message:
In download.file(file_url, file_destination, mode = "wb") :
  InternetOpenUrl failed: '

**Comment by MiRoVaGo** [comment]
Changed the link again could you please check again?
Also, is this only 2.5 or other resolutions as well? (We are most interested in 0.5)

**Comment by Rajani462** [comment]
It's fixed now. It was only with the 2.5 resolution only.

**Comment by Rajani462** [comment]
How about updating the downloading function to start or resume downloading from where it stopped rather than downloading again the existing data. Because whenever it stops/interrupts and I rerun the function it is used to start again from the beginning (even though all the downloaded data exits prior to the error).
