### ISSUE TITLE
Cannot build the package

### ISSUE THREAD

**Issue by imarkonis** [MiRoVaGo/pRecipe#2]
Error message: "package ‘rhdf5’ is not available (for R version 4.0.2)"

**Comment by imarkonis** [comment]
Updated to 4.0.3 and the problem persists.

**Comment by MiRoVaGo** [comment]
Modified description to check for rhdf5 in Bioconductor (it is not available in CRAN)
For what I read that should fix it
@imarkonis could you please check if you can build it now?

**Comment by imarkonis** [comment]
@MiRoVaGo Still same error: dependency 'rhdf5' is not available for package 'pRecipe'

**Comment by MiRoVaGo** [comment]
@imarkonis changed description again and made the execution of download_gpm to install biocmanager and rhdf5
Let me know if you can build now

**Comment by imarkonis** [comment]
@MiRoVaGo Different error this time: Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'rhdf5
